/*
 * Course 90.301
 * Assignment #4-5
 * Last modified: 03/20/2015
 */

package oivancic.view.inputforms;

import oivancic.baseclasses.Classroom;
import oivancic.data.DataContainer;

/**
 *
 * @author Olga Ivancic
 */
public class AddClassroomsWindow extends javax.swing.JFrame 
{

    DataContainer datacontainer; // local data container for storing Classroom data
    
    /**
     * Creates new form AddClassrooms
     */
    public AddClassroomsWindow(DataContainer datacontainer) 
    {
        initComponents();
        this.datacontainer = datacontainer;
    }
    
    /**
     * Empties all the fields on the form
     */
    private void clearAllFields() {
        
        this.classroomNumberField.setText("");
        this.RoomStatusComboBox.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addClassroomsLabel = new javax.swing.JLabel();
        saveClassroomButton = new javax.swing.JButton();
        clearClassroomButton = new javax.swing.JButton();
        closeAddClassroomButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        roomStatusLabel = new javax.swing.JLabel();
        classroomNumberLabel = new javax.swing.JLabel();
        classroomNumberField = new javax.swing.JTextField();
        RoomStatusComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addClassroomsLabel.setText("Add Classrooms");

        saveClassroomButton.setText("Save");
        saveClassroomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveClassroomButtonActionPerformed(evt);
            }
        });

        clearClassroomButton.setText("Clear");
        clearClassroomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearClassroomButtonActionPerformed(evt);
            }
        });

        closeAddClassroomButton.setText("Close");
        closeAddClassroomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAddClassroomButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        roomStatusLabel.setText("Room Status:");

        classroomNumberLabel.setText("Classroom Number:");

        RoomStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lab", "Classroom", "lecture Hall" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classroomNumberLabel)
                    .addComponent(roomStatusLabel))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RoomStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classroomNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classroomNumberLabel)
                    .addComponent(classroomNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomStatusLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addClassroomsLabel)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(saveClassroomButton)
                .addGap(50, 50, 50)
                .addComponent(clearClassroomButton)
                .addGap(50, 50, 50)
                .addComponent(closeAddClassroomButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(addClassroomsLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveClassroomButton)
                    .addComponent(clearClassroomButton)
                    .addComponent(closeAddClassroomButton))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeAddClassroomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAddClassroomButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeAddClassroomButtonActionPerformed

    private void clearClassroomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearClassroomButtonActionPerformed
        clearAllFields();
    }//GEN-LAST:event_clearClassroomButtonActionPerformed

    private void saveClassroomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveClassroomButtonActionPerformed
        // Creating a new Classroom object to store data entered on the form
        Classroom aClassroom = new Classroom();
        
        // Retrieve the data from the form into the aClassroom object
        String roomNumber = this.classroomNumberField.getText();
        String roomStatusSelected = (String) this.RoomStatusComboBox.getSelectedItem();
        char status = roomStatusSelected.charAt(0);
        
        // Store in the Classroom object
        aClassroom.setRoomNumber(roomNumber);
        aClassroom.setStatus(status);
        
        // Add stored data to the list in the datacontainer
        datacontainer.getListOfClassrooms().add(aClassroom);
        
        // Clear data from the fields
        clearAllFields();
    }//GEN-LAST:event_saveClassroomButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox RoomStatusComboBox;
    private javax.swing.JLabel addClassroomsLabel;
    private javax.swing.JTextField classroomNumberField;
    private javax.swing.JLabel classroomNumberLabel;
    private javax.swing.JButton clearClassroomButton;
    private javax.swing.JButton closeAddClassroomButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel roomStatusLabel;
    private javax.swing.JButton saveClassroomButton;
    // End of variables declaration//GEN-END:variables
}
