/*
 * Course 90.301
 * Assignment #4-5
 * Last modified: 03/17/2015
 */

package oivancic.view.inputforms;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import oivancic.baseclasses.Classroom;
import oivancic.baseclasses.OfferedClass;
import oivancic.data.DataContainer;

/**
 *
 * @author Olga Ivancic
 */
public class AddClassesWindow extends javax.swing.JFrame {
    
    DataContainer datacontainer; // local data container for storing Offered Class data
    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();

    /**
     * Creates new form AddClasses
     */
    public AddClassesWindow(DataContainer datacontainer) {
        initComponents();
        this.datacontainer = datacontainer;
        
        // Create the content of the Select Classrooms combo box by adding elements
        // from the List of Classrooms Array List from the datacontainer
        ArrayList<Classroom> listOfClassrooms = this.datacontainer.getListOfClassrooms();
        for (Classroom classroom : listOfClassrooms) {
            comboBoxModel.addElement(classroom.getRoomNumber());
        }
        
        // Set combo box model
        this.classroomChoiceComboBox.setModel(comboBoxModel);
    }
    /**
     * Empties all the fields on the form
     */
    private void clearAllFields() {
        
        this.classNameField.setText("");
        this.classIdNumberField.setText("");
        this.classroomChoiceComboBox.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addClassesLabel = new javax.swing.JLabel();
        saveClassButton = new javax.swing.JButton();
        clearClassButton = new javax.swing.JButton();
        closeAddClassroomButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        classNameLabel = new javax.swing.JLabel();
        classroomChoiceComboBox = new javax.swing.JComboBox();
        classNameField = new javax.swing.JTextField();
        classIdNumberField = new javax.swing.JTextField();
        classIdNumberLabel = new javax.swing.JLabel();
        classroomLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addClassesLabel.setText("Add Classes");

        saveClassButton.setText("Save");
        saveClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveClassButtonActionPerformed(evt);
            }
        });

        clearClassButton.setText("Clear");
        clearClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearClassButtonActionPerformed(evt);
            }
        });

        closeAddClassroomButton.setText("Close");
        closeAddClassroomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAddClassroomButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        classNameLabel.setText("Class Name:");

        classNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classNameFieldActionPerformed(evt);
            }
        });

        classIdNumberLabel.setText("Class ID Number:");

        classroomLabel.setText("Classroom:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classNameLabel)
                    .addComponent(classIdNumberLabel)
                    .addComponent(classroomLabel))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(classroomChoiceComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(classIdNumberField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classNameLabel)
                    .addComponent(classNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classIdNumberLabel)
                    .addComponent(classIdNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classroomLabel)
                    .addComponent(classroomChoiceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(saveClassButton)
                        .addGap(50, 50, 50)
                        .addComponent(clearClassButton)
                        .addGap(50, 50, 50)
                        .addComponent(closeAddClassroomButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addClassesLabel)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addClassesLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveClassButton)
                    .addComponent(clearClassButton)
                    .addComponent(closeAddClassroomButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classNameFieldActionPerformed

    private void saveClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveClassButtonActionPerformed
        // create an OfferedClass object to store data from the form
        OfferedClass anOfferedClass = new OfferedClass();
        
        // Retrieve the data from the text fields
        String className = this.classNameField.getText();
        String classId = this.classIdNumberField.getText();
               
        // Convert variables to the variable types appropriate for an object of 
        // OfferedClass type. Store data in the created OfferedClass object
        anOfferedClass.setClassName(className);
        anOfferedClass.setClassIdNumber(Float.parseFloat(classId));
        
        // Retrieve the correct classroom from the datacontainer and link it to this class
        for (Classroom aClassroom : this.datacontainer.getListOfClassrooms()) {
            
            // Retrieve the selected classroom from the combo box
            String roomNumber = (String) this.classroomChoiceComboBox.getSelectedItem();
            
            // Find the matching classroom in the datacontainer and link it to anOfferedClass
            if (aClassroom.getRoomNumber().equals(roomNumber)) {
                anOfferedClass.setClassroom(aClassroom);
            }
        }
        
        // Save anOfferedClass object in the datacontainer
        datacontainer.getListOfClasses().add(anOfferedClass);
        
        // Clear all the fields
        clearAllFields();
    }//GEN-LAST:event_saveClassButtonActionPerformed

    private void clearClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearClassButtonActionPerformed
        clearAllFields();
    }//GEN-LAST:event_clearClassButtonActionPerformed

    private void closeAddClassroomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAddClassroomButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeAddClassroomButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addClassesLabel;
    private javax.swing.JTextField classIdNumberField;
    private javax.swing.JLabel classIdNumberLabel;
    private javax.swing.JTextField classNameField;
    private javax.swing.JLabel classNameLabel;
    private javax.swing.JComboBox classroomChoiceComboBox;
    private javax.swing.JLabel classroomLabel;
    private javax.swing.JButton clearClassButton;
    private javax.swing.JButton closeAddClassroomButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveClassButton;
    // End of variables declaration//GEN-END:variables
}
