/*
 * Course 90.301
 * Assignment #4-5
 * Last modified: 03/05/2015
 */

package oivancic.view.inputforms;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import oivancic.baseclasses.Faculty;
import oivancic.baseclasses.FacultyClass;
import oivancic.baseclasses.OfferedClass;
import oivancic.data.DataContainer;

/**
 *
 * @author Olga Ivancic
 */
public class AddFacultyWindow extends javax.swing.JFrame {

    DataContainer datacontainer; // local data container for storing Faculty data
    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
    private Faculty newFacultyMember;
    
    /**
     * Creates new form AddFaculty
     */
    public AddFacultyWindow(DataContainer datacontainer) {
        initComponents();
        this.datacontainer = datacontainer;
        
        // Add all the classrooms from the data container list to drop down on 
        // the form using a data model
        ArrayList<OfferedClass> listOfClasses = this.datacontainer.getListOfClasses();
        for (OfferedClass aClass : listOfClasses) {
            comboBoxModel.addElement(aClass.getClassName());
        }
        
        // Attach the list model to the drop down on the form
        this.selectClassesComboBox.setModel(comboBoxModel);
    }
    
    /**
     * Empties all the fields on the form
     */
    private void clearAllFields() {
        
        this.FacultyAddressField.setText("");
        this.FacultySocialSecurityNumberField.setText("");
        this.FacultytNameField.setText("");
        this.facultyDayOfBirthField.setText("dd");
        this.facultyDayOfHireField.setText("dd");
        this.facultyDayOfTerminationField.setText("dd");
        this.facultyMonthOfBirthField.setText("mm");
        this.facultyMonthOfHireField.setText("mm");
        this.facultyMonthOfTerminationField.setText("mm");
        this.facultySalaryField.setText("0.00");
        this.facultyStatusComboBox.setSelectedIndex(0);
        this.facultyYearOfBirthField.setText("yyyy");
        this.facultyYearOfHireField.setText("yyyy");
        this.facultyYearOfTerminationField.setText("yyyy");
        this.selectClassesComboBox.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addFacultyLabel = new javax.swing.JLabel();
        clearFacultyButton = new javax.swing.JButton();
        closeFacultyButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        FacultyDateOfBirthLabel = new javax.swing.JLabel();
        facultyYearOfBirthField = new javax.swing.JTextField();
        facultyDayOfTerminationField = new javax.swing.JTextField();
        facultyDayOfBirthField = new javax.swing.JTextField();
        FacultySocialSecurityNumberLabel = new javax.swing.JLabel();
        facultyStatusComboBox = new javax.swing.JComboBox();
        FacultySocialSecurityNumberField = new javax.swing.JTextField();
        facultyYearOfTerminationField = new javax.swing.JTextField();
        FacultyDateOfTerminationLabel = new javax.swing.JLabel();
        facultyStatusLabel = new javax.swing.JLabel();
        FacultyAddressField = new javax.swing.JTextField();
        facultyMonthOfBirthField = new javax.swing.JTextField();
        FacultyNameLabel = new javax.swing.JLabel();
        facultySalaryField = new javax.swing.JTextField();
        facultyYearOfHireField = new javax.swing.JTextField();
        facultyMonthOfHireField = new javax.swing.JTextField();
        facultyDayOfHireField = new javax.swing.JTextField();
        facultySalaryLabel = new javax.swing.JLabel();
        FacultyAddressLabel = new javax.swing.JLabel();
        FacultyDateOfHireLabel = new javax.swing.JLabel();
        facultyMonthOfTerminationField = new javax.swing.JTextField();
        FacultytNameField = new javax.swing.JTextField();
        dollarSignLabel = new javax.swing.JLabel();
        saveFacultyButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        addClassButton = new javax.swing.JButton();
        selectClassesComboBox = new javax.swing.JComboBox();
        addClassesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addFacultyLabel.setText("Add Faculty");

        clearFacultyButton.setText("Clear");
        clearFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFacultyButtonActionPerformed(evt);
            }
        });

        closeFacultyButton.setText("Close");
        closeFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFacultyButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FacultyDateOfBirthLabel.setText("Date Of Birth:");

        facultyYearOfBirthField.setText("yyyy");
        facultyYearOfBirthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyYearOfBirthFieldActionPerformed(evt);
            }
        });

        facultyDayOfTerminationField.setText("dd");
        facultyDayOfTerminationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyDayOfTerminationFieldActionPerformed(evt);
            }
        });

        facultyDayOfBirthField.setText("dd");
        facultyDayOfBirthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyDayOfBirthFieldActionPerformed(evt);
            }
        });

        FacultySocialSecurityNumberLabel.setText("Social Security Number:");

        facultyStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Full Time", "Part Time" }));
        facultyStatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyStatusComboBoxActionPerformed(evt);
            }
        });

        FacultySocialSecurityNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultySocialSecurityNumberFieldActionPerformed(evt);
            }
        });

        facultyYearOfTerminationField.setText("yyyy");
        facultyYearOfTerminationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyYearOfTerminationFieldActionPerformed(evt);
            }
        });

        FacultyDateOfTerminationLabel.setText("Date Of Termination:");

        facultyStatusLabel.setText("Status:");

        FacultyAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyAddressFieldActionPerformed(evt);
            }
        });

        facultyMonthOfBirthField.setText("mm");
        facultyMonthOfBirthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyMonthOfBirthFieldActionPerformed(evt);
            }
        });

        FacultyNameLabel.setText("Name:");

        facultySalaryField.setText("0.00");

        facultyYearOfHireField.setText("yyyy");
        facultyYearOfHireField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyYearOfHireFieldActionPerformed(evt);
            }
        });

        facultyMonthOfHireField.setText("mm");
        facultyMonthOfHireField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyMonthOfHireFieldActionPerformed(evt);
            }
        });

        facultyDayOfHireField.setText("dd");
        facultyDayOfHireField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyDayOfHireFieldActionPerformed(evt);
            }
        });

        facultySalaryLabel.setText("Salary:");

        FacultyAddressLabel.setText("Address:");

        FacultyDateOfHireLabel.setText("Date Of Hire:");

        facultyMonthOfTerminationField.setText("mm");
        facultyMonthOfTerminationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyMonthOfTerminationFieldActionPerformed(evt);
            }
        });

        FacultytNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultytNameFieldActionPerformed(evt);
            }
        });

        dollarSignLabel.setText("$");

        saveFacultyButton.setText("Save");
        saveFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFacultyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FacultyNameLabel)
                                    .addComponent(FacultyAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FacultytNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FacultyAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(FacultySocialSecurityNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(FacultySocialSecurityNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FacultyDateOfHireLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(FacultyDateOfBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(FacultyDateOfTerminationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(facultyStatusLabel))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(facultyStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(facultyMonthOfTerminationField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(facultyDayOfTerminationField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(facultyMonthOfHireField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(facultyDayOfHireField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(facultyMonthOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(facultyDayOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(facultyYearOfTerminationField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(facultyYearOfHireField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(facultyYearOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(facultySalaryLabel)
                                .addGap(102, 102, 102)
                                .addComponent(dollarSignLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facultySalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(saveFacultyButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FacultyNameLabel)
                            .addComponent(FacultytNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FacultyAddressLabel)
                            .addComponent(FacultyAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FacultySocialSecurityNumberLabel)
                            .addComponent(FacultySocialSecurityNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FacultyDateOfBirthLabel)
                            .addComponent(facultyMonthOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facultyDayOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FacultyDateOfHireLabel)
                            .addComponent(facultyMonthOfHireField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facultyDayOfHireField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FacultyDateOfTerminationLabel)
                            .addComponent(facultyMonthOfTerminationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facultyDayOfTerminationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(facultyYearOfBirthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(facultyYearOfHireField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(facultyYearOfTerminationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(facultySalaryLabel)
                        .addComponent(facultySalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dollarSignLabel))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(facultyStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(facultyStatusLabel)))
                .addGap(27, 27, 27)
                .addComponent(saveFacultyButton)
                .addGap(152, 152, 152))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        addClassButton.setText("Add Class");
        addClassButton.setEnabled(false);
        addClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassButtonActionPerformed(evt);
            }
        });

        selectClassesComboBox.setToolTipText("");

        addClassesLabel.setText("Add Classes to the last saved faculty member:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addClassesLabel)
                .addGap(84, 84, 84)
                .addComponent(selectClassesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(addClassButton)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addClassesLabel)
                    .addComponent(selectClassesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addClassButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(addFacultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(clearFacultyButton)
                        .addGap(42, 42, 42)
                        .addComponent(closeFacultyButton)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addFacultyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearFacultyButton)
                    .addComponent(closeFacultyButton))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FacultySocialSecurityNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultySocialSecurityNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultySocialSecurityNumberFieldActionPerformed

    private void FacultyAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultyAddressFieldActionPerformed

    private void FacultytNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultytNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FacultytNameFieldActionPerformed

    private void facultyYearOfBirthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyYearOfBirthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyYearOfBirthFieldActionPerformed

    private void facultyMonthOfBirthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyMonthOfBirthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyMonthOfBirthFieldActionPerformed

    private void facultyDayOfBirthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyDayOfBirthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyDayOfBirthFieldActionPerformed

    private void facultyYearOfHireFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyYearOfHireFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyYearOfHireFieldActionPerformed

    private void facultyMonthOfHireFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyMonthOfHireFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyMonthOfHireFieldActionPerformed

    private void facultyDayOfHireFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyDayOfHireFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyDayOfHireFieldActionPerformed

    private void facultyYearOfTerminationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyYearOfTerminationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyYearOfTerminationFieldActionPerformed

    private void facultyMonthOfTerminationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyMonthOfTerminationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyMonthOfTerminationFieldActionPerformed

    private void facultyDayOfTerminationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyDayOfTerminationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyDayOfTerminationFieldActionPerformed

    private void facultyStatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyStatusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyStatusComboBoxActionPerformed

    private void saveFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFacultyButtonActionPerformed
        // create a Faculty object
        newFacultyMember = new Faculty();
        
        // Retrive the data from the form
        String address = this.FacultyAddressField.getText();
        String socialSecurityNumber = this.FacultySocialSecurityNumberField.getText();
        String name = this.FacultytNameField.getText();
        String dayOfBirth = this.facultyDayOfBirthField.getText();
        String dayOfHire = this.facultyDayOfHireField.getText();
        String dayOfTermination = this.facultyDayOfTerminationField.getText();
        String monthOfBirth = this.facultyMonthOfBirthField.getText();
        String monthOfHire = this.facultyMonthOfHireField.getText();
        String monthOfTermination = this.facultyMonthOfTerminationField.getText();
        String salary = this.facultySalaryField.getText();
        String statusSelected = (String) this.facultyStatusComboBox.getSelectedItem();
        String yearOfBirth = this.facultyYearOfBirthField.getText();
        String yearOfHire = this.facultyYearOfHireField.getText();
        String yearOfTermination = this.facultyYearOfTerminationField.getText();
        
        // Convert variables to the variable types appropriate for an object of 
        // Faculty type. Store data in the created Faculty object
        newFacultyMember.setAddress(address);
        newFacultyMember.setSocialSecurityNumber(socialSecurityNumber);
        newFacultyMember.setName(name);
        
        int intDayOfBirth = Integer.parseInt(dayOfBirth);
        int intMonthOfBirth = Integer.parseInt(monthOfBirth);
        int intYearOfBirth = Integer.parseInt(yearOfBirth);
        newFacultyMember.setDateOfBirth(intYearOfBirth, intMonthOfBirth, intDayOfBirth);
        
        int intDayOfHire = Integer.parseInt(dayOfHire);
        int intMonthOfHire = Integer.parseInt(monthOfHire);
        int intYearOfHire = Integer.parseInt(yearOfHire);
        newFacultyMember.setDateOfHire(intYearOfHire, intMonthOfHire, intDayOfHire);
        
        int intDayOfTermination = Integer.parseInt(dayOfTermination);
        int intMonthOfTermination = Integer.parseInt(monthOfTermination);
        int intYearOfTermination = Integer.parseInt(yearOfTermination);
        newFacultyMember.setDateOfTermination(intYearOfTermination, intMonthOfTermination, intDayOfTermination);
        
        newFacultyMember.setSalary(Double.parseDouble(salary));
        
        char status = statusSelected.charAt(0);
        newFacultyMember.setStatus(status);
        
        // Save the data in the datacontainer
        datacontainer.getListOfFaculty().add(newFacultyMember);
        
        // Enable AddClass button
        this.addClassButton.setEnabled(true);
        
        // Clear all fields for the next entry
        clearAllFields();
        
    }//GEN-LAST:event_saveFacultyButtonActionPerformed

    private void clearFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFacultyButtonActionPerformed
        clearAllFields();
    }//GEN-LAST:event_clearFacultyButtonActionPerformed

    private void closeFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFacultyButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeFacultyButtonActionPerformed

    private void addClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassButtonActionPerformed
        // Retrieve selected class from the combo box and use it to create a facultyclass
       String selectedClass = (String) this.selectClassesComboBox.getSelectedItem();
       FacultyClass newFacultyClass = new FacultyClass();
       ArrayList<OfferedClass> offeredClasses = new ArrayList<OfferedClass>();
       
       // Retrieve the correct OfferedClass from the datacontainer and link it to this FacultyClass
        for (OfferedClass anOfferedClass : offeredClasses) {
            if (anOfferedClass.getClassName().equals(selectedClass)) {
                newFacultyClass.setClassIdNumber(anOfferedClass.getClassIdNumber());
                newFacultyClass.setClassName(anOfferedClass.getClassName());
                newFacultyClass.setClassroom(anOfferedClass.getClassroom());
            }
        }
       
       // Retrieve the SSN for the last saved student
       String ssn = this.newFacultyMember.getSocialSecurityNumber();
       
       // Open an AddStudentsToFacultyClass window and pass the facultyClass object to it
       AddStudentsToFacultyClass addEnrolledStudentsWindow = new AddStudentsToFacultyClass(datacontainer, newFacultyClass, ssn);
       addEnrolledStudentsWindow.setVisible(true);
    }//GEN-LAST:event_addClassButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FacultyAddressField;
    private javax.swing.JLabel FacultyAddressLabel;
    private javax.swing.JLabel FacultyDateOfBirthLabel;
    private javax.swing.JLabel FacultyDateOfHireLabel;
    private javax.swing.JLabel FacultyDateOfTerminationLabel;
    private javax.swing.JLabel FacultyNameLabel;
    private javax.swing.JTextField FacultySocialSecurityNumberField;
    private javax.swing.JLabel FacultySocialSecurityNumberLabel;
    private javax.swing.JTextField FacultytNameField;
    private javax.swing.JButton addClassButton;
    private javax.swing.JLabel addClassesLabel;
    private javax.swing.JLabel addFacultyLabel;
    private javax.swing.JButton clearFacultyButton;
    private javax.swing.JButton closeFacultyButton;
    private javax.swing.JLabel dollarSignLabel;
    private javax.swing.JTextField facultyDayOfBirthField;
    private javax.swing.JTextField facultyDayOfHireField;
    private javax.swing.JTextField facultyDayOfTerminationField;
    private javax.swing.JTextField facultyMonthOfBirthField;
    private javax.swing.JTextField facultyMonthOfHireField;
    private javax.swing.JTextField facultyMonthOfTerminationField;
    private javax.swing.JTextField facultySalaryField;
    private javax.swing.JLabel facultySalaryLabel;
    private javax.swing.JComboBox facultyStatusComboBox;
    private javax.swing.JLabel facultyStatusLabel;
    private javax.swing.JTextField facultyYearOfBirthField;
    private javax.swing.JTextField facultyYearOfHireField;
    private javax.swing.JTextField facultyYearOfTerminationField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton saveFacultyButton;
    private javax.swing.JComboBox selectClassesComboBox;
    // End of variables declaration//GEN-END:variables
}
