/*
 * Course 90.301
 * Assignment #4-5
 * Last modified: 03/08/2015
 */

package oivancic.view.reports;

import static java.lang.String.valueOf;
import java.util.ArrayList;
import oivancic.baseclasses.Faculty;
import oivancic.data.DataContainer;
import static oivancic.utilities.DateFormatter.getFormattedDate;

/**
 *
 * @author Olga Ivancic
 */
public class ListAllFacultyWindow extends javax.swing.JFrame {
    
    DataContainer datacontainer; // local copy of the datacontainer that holds all the data
    
    /**
     * Creates new form ListAllFacultyWindow
     */
    public ListAllFacultyWindow(DataContainer datacontainer) {
        initComponents();
        this.datacontainer = datacontainer;
        
        // Create the header of the "table" for the text area
        String facultyReportText = "Name\tAddress\tSSN\tDate of Birth\tDate of Hire\tDate of Termination\t"
                + "Salary, $\tStatus\tClasses\n";
        
        // Get a list of faculty from the datacontainer
        ArrayList<Faculty> listOfFaculty = this.datacontainer.getListOfFaculty();
        
        // Loop through the List of Faculty to add data to the facultyReportText
        for (int i = 0; i < listOfFaculty.size(); i++) {
            Faculty facultyMember = listOfFaculty.get(i);
            String name = facultyMember.getName();
            String address = facultyMember.getAddress();
            String ssn = facultyMember.getSocialSecurityNumber();
            String dob = getFormattedDate(facultyMember.getDateOfBirth());
            String dateOfHire = getFormattedDate(facultyMember.getDateOfHire());
            String dateOfTermination = getFormattedDate(facultyMember.getDateOfTermination());
            String salary = valueOf(facultyMember.getSalary());
            char charStatus = facultyMember.getStatus();
            String status;
            if (charStatus == 'P')
                status = "Part Time";
            else
                status = "Full Time";
            String classes = facultyMember.getClasses().toString();
            
            facultyReportText += name;
            facultyReportText += "\t";
            facultyReportText += address;
            facultyReportText += "\t";
            facultyReportText += ssn;
            facultyReportText += "\t";
            facultyReportText += dob;
            facultyReportText += "\t";
            facultyReportText += dateOfHire;
            facultyReportText += "\t";
            facultyReportText += dateOfTermination;
            facultyReportText += "\t";
            facultyReportText += salary;
            facultyReportText += "\t";
            facultyReportText += status;
            facultyReportText += "\t";
            facultyReportText += classes;
            facultyReportText += "\n";
        }
        
        // Set text for the textarea
        this.listOfFacultyTextArea.setText(facultyReportText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOfFacultyTextArea = new javax.swing.JTextArea();
        closeListAllFacultyWindowButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("List of All Faculty Members");

        listOfFacultyTextArea.setEditable(false);
        listOfFacultyTextArea.setColumns(20);
        listOfFacultyTextArea.setRows(5);
        jScrollPane1.setViewportView(listOfFacultyTextArea);

        closeListAllFacultyWindowButton.setText("Close");
        closeListAllFacultyWindowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeListAllFacultyWindowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel1)
                .addContainerGap(356, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeListAllFacultyWindowButton)
                .addGap(379, 379, 379))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(closeListAllFacultyWindowButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeListAllFacultyWindowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeListAllFacultyWindowButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeListAllFacultyWindowButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeListAllFacultyWindowButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listOfFacultyTextArea;
    // End of variables declaration//GEN-END:variables
}
