/*
 * Course 90.301
 * Assignment #4-5
 * Last modified: 03/19/2015
 */

package oivancic.view.reports;

import static java.lang.String.valueOf;
import java.util.ArrayList;
import oivancic.baseclasses.OfferedClass;
import oivancic.data.DataContainer;

/**
 *
 * @author Olga Ivancic
 */
public class ListAllClassesWindow extends javax.swing.JFrame {

    DataContainer datacontainer; // local copy of the datacontainer that holds all the data
    
    /**
     * Creates new form ListAllClassesWindow
     */
    public ListAllClassesWindow(DataContainer datacontainer) {
        initComponents();
        this.datacontainer = datacontainer;
        
        // Create the header of the "table" for the text area
        String classesReportText = "Class Name\tClass ID Number\tClassroom\n";
        
        // Get a list of classes from the datacontainer
        ArrayList<OfferedClass> listOfClasses = this.datacontainer.getListOfClasses();
        
        // Loop through the List of Classes to add data to the classesReportText
        for (int i = 0; i < listOfClasses.size(); i++) {
            OfferedClass aClass = listOfClasses.get(i);
            String className = aClass.getClassName();
            String classIdNumber = valueOf(aClass.getClassIdNumber());
            String classroom = aClass.getClassroom().toString();
            classesReportText += className;
            classesReportText += "\t";
            classesReportText += classIdNumber;
            classesReportText += "\t";
            classesReportText += classroom;
            classesReportText += "\n";
        }
        
        // Set text for the textarea
        this.listOfClassesTextArea.setText(classesReportText);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listAllClassesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOfClassesTextArea = new javax.swing.JTextArea();
        closeListAllClassesWindowButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listAllClassesLabel.setText("List of All Offered Classes");

        listOfClassesTextArea.setEditable(false);
        listOfClassesTextArea.setColumns(20);
        listOfClassesTextArea.setRows(5);
        jScrollPane1.setViewportView(listOfClassesTextArea);

        closeListAllClassesWindowButton.setText("Close");
        closeListAllClassesWindowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeListAllClassesWindowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeListAllClassesWindowButton)
                .addGap(229, 229, 229))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(listAllClassesLabel)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listAllClassesLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(closeListAllClassesWindowButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeListAllClassesWindowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeListAllClassesWindowButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeListAllClassesWindowButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeListAllClassesWindowButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel listAllClassesLabel;
    private javax.swing.JTextArea listOfClassesTextArea;
    // End of variables declaration//GEN-END:variables
}
