/*
 * Course 90.301
 * Assignment #4-5
 * Last modified: 03/08/2015
 */

package oivancic.view.applicationmain;

import oivancic.data.DataContainer;
import oivancic.view.inputforms.AddClassesWindow;
import oivancic.view.inputforms.AddClassroomsWindow;
import oivancic.view.inputforms.AddFacultyWindow;
import oivancic.view.inputforms.AddStudentsWindow;
import oivancic.view.reports.ListAllClassesWindow;
import oivancic.view.reports.ListAllClassroomsWindow;
import oivancic.view.reports.ListAllFacultyWindow;
import oivancic.view.reports.ListAllStudentsWindow;

/**
 *
 * @author Olga Ivancic
 */
public class MainMenuWindow extends javax.swing.JFrame {
    
    private DataContainer datacontainer = new DataContainer(); // contains all the data that is passed
                                         // to the "Add" and "List" windows
    
    public MainMenuWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuBar = new javax.swing.JMenuBar();
        studentsMainMenu = new javax.swing.JMenu();
        addStudentsMainMenuItem = new javax.swing.JMenuItem();
        listStudentsMainMenuItem = new javax.swing.JMenuItem();
        facultyMainMenu = new javax.swing.JMenu();
        addFacultyMainMenuItem = new javax.swing.JMenuItem();
        listFacultyMainMenuItem = new javax.swing.JMenuItem();
        classroomsMainMenu = new javax.swing.JMenu();
        addClassroomsMainMenuItem = new javax.swing.JMenuItem();
        listClassroomsMainMenuItem = new javax.swing.JMenuItem();
        classesMainMenu = new javax.swing.JMenu();
        addClassesMainMenuItem = new javax.swing.JMenuItem();
        listClassesMainMenuItem = new javax.swing.JMenuItem();
        helpMainMenu = new javax.swing.JMenu();
        aboutMainMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        studentsMainMenu.setText("Students");
        studentsMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsMainMenuActionPerformed(evt);
            }
        });

        addStudentsMainMenuItem.setText("Add Students");
        addStudentsMainMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentsMainMenuItemActionPerformed(evt);
            }
        });
        studentsMainMenu.add(addStudentsMainMenuItem);

        listStudentsMainMenuItem.setText("List All Students");
        listStudentsMainMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStudentsMainMenuItemActionPerformed(evt);
            }
        });
        studentsMainMenu.add(listStudentsMainMenuItem);

        mainMenuBar.add(studentsMainMenu);

        facultyMainMenu.setText("Faculty");
        facultyMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyMainMenuActionPerformed(evt);
            }
        });

        addFacultyMainMenuItem.setText("Add Faculty");
        addFacultyMainMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyMainMenuItemActionPerformed(evt);
            }
        });
        facultyMainMenu.add(addFacultyMainMenuItem);

        listFacultyMainMenuItem.setText("List All Faculty");
        listFacultyMainMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listFacultyMainMenuItemActionPerformed(evt);
            }
        });
        facultyMainMenu.add(listFacultyMainMenuItem);

        mainMenuBar.add(facultyMainMenu);

        classroomsMainMenu.setText("Classrooms");
        classroomsMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classroomsMainMenuActionPerformed(evt);
            }
        });

        addClassroomsMainMenuItem.setText("Add Classrooms");
        addClassroomsMainMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassroomsMainMenuItemActionPerformed(evt);
            }
        });
        classroomsMainMenu.add(addClassroomsMainMenuItem);

        listClassroomsMainMenuItem.setText("List All Classrooms");
        listClassroomsMainMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClassroomsMainMenuItemActionPerformed(evt);
            }
        });
        classroomsMainMenu.add(listClassroomsMainMenuItem);

        mainMenuBar.add(classroomsMainMenu);

        classesMainMenu.setText("Classes");
        classesMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classesMainMenuActionPerformed(evt);
            }
        });

        addClassesMainMenuItem.setText("Add Classes");
        addClassesMainMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassesMainMenuItemActionPerformed(evt);
            }
        });
        classesMainMenu.add(addClassesMainMenuItem);

        listClassesMainMenuItem.setText("List All Classes");
        listClassesMainMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClassesMainMenuItemActionPerformed(evt);
            }
        });
        classesMainMenu.add(listClassesMainMenuItem);

        mainMenuBar.add(classesMainMenu);

        helpMainMenu.setText("Help");
        helpMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMainMenuActionPerformed(evt);
            }
        });

        aboutMainMenuItem.setText("About");
        aboutMainMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMainMenuItemActionPerformed(evt);
            }
        });
        helpMainMenu.add(aboutMainMenuItem);

        mainMenuBar.add(helpMainMenu);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addClassroomsMainMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassroomsMainMenuItemActionPerformed
        
        // create a new AddClassrooms window passing the datacontainer
        AddClassroomsWindow newAddClassroom = new AddClassroomsWindow(datacontainer);
        
        // Set size and make window visible
        newAddClassroom.setSize(500, 400);
        newAddClassroom.setVisible(true);
    }//GEN-LAST:event_addClassroomsMainMenuItemActionPerformed

    private void addStudentsMainMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentsMainMenuItemActionPerformed
        
        // create a new AddStudents window passing the datacontainer
        AddStudentsWindow newAddStudent = new AddStudentsWindow(datacontainer);
        
        // Set size and make window visible
        newAddStudent.setSize(735, 485);
        newAddStudent.setVisible(true);
    }//GEN-LAST:event_addStudentsMainMenuItemActionPerformed

    private void studentsMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsMainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentsMainMenuActionPerformed

    private void listStudentsMainMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStudentsMainMenuItemActionPerformed
        
        // create a new ListStudents window passing the datacontainer
        ListAllStudentsWindow newListStudent = new ListAllStudentsWindow(datacontainer);
        
        // Set size and make window visible
        newListStudent.setSize(533, 336);
        newListStudent.setVisible(true);
    }//GEN-LAST:event_listStudentsMainMenuItemActionPerformed

    private void facultyMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyMainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyMainMenuActionPerformed

    private void addFacultyMainMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyMainMenuItemActionPerformed
        
        // create a new AddFaculty window passing the datacontainer
        AddFacultyWindow newAddFacultyMember = new AddFacultyWindow(datacontainer);
        
        // Set size and make window visible
        newAddFacultyMember.setSize(470, 412);
        newAddFacultyMember.setVisible(true);
    }//GEN-LAST:event_addFacultyMainMenuItemActionPerformed

    private void listFacultyMainMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listFacultyMainMenuItemActionPerformed
        
        // create a new ListFaculty window passing the datacontainer
        ListAllFacultyWindow newListFaculty = new ListAllFacultyWindow(datacontainer);
        
        // Set size and make window visible
        newListFaculty.setSize(520, 343);
        newListFaculty.setVisible(true);
    }//GEN-LAST:event_listFacultyMainMenuItemActionPerformed

    private void listClassroomsMainMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClassroomsMainMenuItemActionPerformed
        
        // create a new ListAllClassrooms window object passing the datacontainer
        ListAllClassroomsWindow newListClassrooms = new ListAllClassroomsWindow(datacontainer);
        
        // Set size and make window visible
        newListClassrooms.setSize(528, 343);
        newListClassrooms.setVisible(true);
    }//GEN-LAST:event_listClassroomsMainMenuItemActionPerformed

    private void classroomsMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classroomsMainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classroomsMainMenuActionPerformed

    private void classesMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classesMainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classesMainMenuActionPerformed

    private void addClassesMainMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassesMainMenuItemActionPerformed
        
        // create a new AddClasses window passing the datacontainer
        AddClassesWindow newAddClasses = new AddClassesWindow(datacontainer);
        
        // Set size and make window visible
        newAddClasses.setSize(393, 239);
        newAddClasses.setVisible(true);
    }//GEN-LAST:event_addClassesMainMenuItemActionPerformed

    private void listClassesMainMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClassesMainMenuItemActionPerformed
        
        // create a new ListClasses window passing the datacontainer
        ListAllClassesWindow newListClasses = new ListAllClassesWindow(datacontainer);
        
        // Set size and make window visible
        newListClasses.setSize(521, 416);
        newListClasses.setVisible(true);
    }//GEN-LAST:event_listClassesMainMenuItemActionPerformed

    private void helpMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMainMenuActionPerformed
        
        
    }//GEN-LAST:event_helpMainMenuActionPerformed

    private void aboutMainMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMainMenuItemActionPerformed
        // create a new Help Window and set visible
        HelpWindow newHelpWindow = new HelpWindow();
        newHelpWindow.setVisible(true);
    }//GEN-LAST:event_aboutMainMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMainMenuItem;
    private javax.swing.JMenuItem addClassesMainMenuItem;
    private javax.swing.JMenuItem addClassroomsMainMenuItem;
    private javax.swing.JMenuItem addFacultyMainMenuItem;
    private javax.swing.JMenuItem addStudentsMainMenuItem;
    private javax.swing.JMenu classesMainMenu;
    private javax.swing.JMenu classroomsMainMenu;
    private javax.swing.JMenu facultyMainMenu;
    private javax.swing.JMenu helpMainMenu;
    private javax.swing.JMenuItem listClassesMainMenuItem;
    private javax.swing.JMenuItem listClassroomsMainMenuItem;
    private javax.swing.JMenuItem listFacultyMainMenuItem;
    private javax.swing.JMenuItem listStudentsMainMenuItem;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenu studentsMainMenu;
    // End of variables declaration//GEN-END:variables
}
